---
title: "Graficación en ggplot2 y quarto"
format: 
  html: 
    toc: true
    lang: es
---
# INTRODUCCION
Este documento presenta un conjunto de visualizaciones de datos elaborados con paquetes de lenguaje R como ggplot 2, plotly y DT.

# Carga de bibliotecas
```{r}
#| label:  carga-biblioteca
#| warning: false
#| message: false

library(tidyverse)
library(DT)
library(plotly)
library(gapminder)
```

# carga de datos

## mpg
```{r}
#| label: carga-datos-mpg
#| warning: false
#| code-fold: true

# carga de datos del paquete mpg
mpg |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## diamonds
```{r}
#| label: cargadatos-diamonds-mpg
#| warning: false
#| message: false
#| code-fold: true

# Tabla de datos de diamonds
diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## gapminder
```{r}
#| label: gapminder
#| warning: false
#| message: false
#| code-fold: true


# Tabla de datos de gapminder
diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Covid
```{r}
#| label: carga de archivo CSV Covid
#| warning: false
#| message: false
#| code-fold: true

# Carga del archivo CSV de entrada en un dataframe
# con la función read_delim() de readr
covid_general <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/ministerio-salud/covid/05_30_22_CSV_GENERAL.csv",
    col_select = c(
      "FECHA",
      "positivos",
      "activos",
      "RECUPERADOS",
      "fallecidos",
      "nue_posi",
      "nue_falleci",
      "salon",
      "UCI"
    )
  )

# Cambio de nombre de columnas
covid_general <-
  covid_general |>
  rename(
    fecha = FECHA,
    recuperados = RECUPERADOS,
    nuevos_positivos = nue_posi,
    nuevos_fallecidos = nue_falleci,
    uci = UCI
  )

# Cambio de tipo de datos de la columna fecha, de str a date
covid_general <-
  covid_general |>
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))

# despliegue de datos
covid_general |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## delitos en 2022 en Costa Rica
```{r}
#| label: carga-Delitos-2022
#| warning: false
#| message: false  
#| code-fold: true

# Carga de datos
delitos_2022 <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/oij/estadisticas-policiales/estadisticaspoliciales2022.csv"
  )

# Tabla de datos
delitos_2022 |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```
